{
  "error": {
    "root_cause": [
      {
        "type": "index_not_found_exception",
        "reason": "no such index",
        "resource.type": "index_or_alias",
        "resource.id": "dating_test",
        "index_uuid": "_na_",
        "index": "dating_test"
      }
    ],
    "type": "index_not_found_exception",
    "reason": "no such index",
    "resource.type": "index_or_alias",
    "resource.id": "dating_test",
    "index_uuid": "_na_",
    "index": "dating_test"
  },
  "status": 404
}
